name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: Install Dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        working-directory: ./client
        run: npm run build
        env:
          REACT_APP_API_KEY=${{ secrets.API_KEY }}
          REACT_APP_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL=${{ secrets.DATABASE_URL }}
          REACT_APP_PROJECT_ID=${{ secrets.PROJECT_ID }}
          REACT_APP_STOREAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=simple-race-timer
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client/build 
